package ua.com.testes.manager.web.page;


public enum PageDetailError {

    FIRM_NAME_EMPTY, FIRM_NAME_NOT_UNIQUE, PIPOL_FIO_EMPTY,
    CONTACT_DESCRIPTION_EMPTY, SECTION_NOT_SELECT, STATUS_NOT_SELECT,
    FIRM_NOT_SELECT, PIPOL_FIO_NOT_UNIQUE, PIPOL_NOT_SELECT,
    CONTACT_REPEATE_DATE_INCORRENT

}